#APPLICATION BROWSER
browser = chrome
#APPLICATION URL
url = https://www.naukri.com/nlogin/login?err=1
#APPLICATION USERNAME AND PASSWORD
username = devaraj21294@gmail.com
password = Devaraj@21294
#input 
expErrorMsg= Please remove your employment if you want to mark yourself as fresher
title= Devarajan Sadhasivam
resumeTitle= Devarajan_QAtester_3yrs.pdf
#FILE PATHS
excelPath= C:\\Users\\admin\\eclipse-workspace\\Cucumber_Project\\src\\test\\resources\\Excel.xlsx
extendStart= C:\\\Users\\admin\\eclipse-workspace\\NAUKRI_PROJECT\\Reports
extendEnd= C:\\\Users\\admin\\eclipse-workspace\\NAUKRI_PROJECT\\Reports\\Index.html

